routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


if (!lr_is_installed()) {

    //Route::group( [ 'middleware' => 'web' ], function () {

    Route::get(
        '/lr-install',
        [
            'uses' => 'Admin\InstallController@showInstall',
        ]
    );
    Route::post(
        '/lr-install',
        [
            'uses' => 'Admin\InstallController@installCms',
        ]
    );
    //});


}


if (!lr_is_installed()) return;
// Localization
Route::get('/js/lang.js', function () {
    $strings = Cache::rememberForever('lang.js', function () {
        $lang = config('app.locale');

        $files = glob(resource_path('lang/' . $lang . '/*.php'));
        $strings = [];

        foreach ($files as $file) {
            $name = basename($file, '.php');
            $strings[$name] = require $file;
        }

        return $strings;
    });

    header('Content-Type: text/javascript');
    echo ('window.i18n = ' . json_encode($strings) . ';');
    exit();
})->name('assets.lang');


// we regenerate thumbails
Route::get('/uploads/{img}/{h}/{w}', function ($filePath, $h = 200, $w = 200) {

    $filePath = public_path("/uploads/$filePath");

    $img = Image::cache(function ($image) use ($filePath, $h, $w) {
        $image->make($filePath)->fit($h, $w); // This line works fine without being wrapped in `cache`
    }, 1, true);


    return $img->response();


    // return Image::make(public_path("/uploads/$filePath"))->fit($h, $w)->response();
});

// we regenerate thumbails
Route::get('storage/uploads/{img}/{h}/{w}', function ($filePath, $h = 200, $w = 200) {

    $filePath = storage_path("app/public/uploads/$filePath");


    $img = Image::cache(function ($image) use ($filePath, $h, $w) {
        $image->make($filePath)->fit($h, $w); // This line works fine without being wrapped in `cache`
    }, 10, true);


    //	dd($filePath);
    return $img->response();


    // return Image::make(public_path("/uploads/$filePath"))->fit($h, $w)->response();
});


Route::group(['prefix' => Corp\Http\Middleware\LocaleMiddleware::getLocale()], function () {


    //admin
    Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {

        //admin
        Route::get(
            '/',
            [
                'uses' => 'Admin\IndexController@index',
                'as' => 'adminIndex'
            ]
        );

        // posts


        Route::resource('posts', 'Admin\PostsController', [
            'as' => 'admin'
        ]);

        Route::post('posts/clone', 'Admin\PostsController@Clone')->name('admin.posts.clone');

        Route::resource('comments', 'Admin\CommentsController', [
            'as' => 'admin'
        ]);

        // comments
        //		Route::resource( 'comments', 'Admin\CommentsController', [
        //			'as' => 'comments'
        //		] );


        // pages
        Route::resource('pages', 'Admin\PageController', [
            'as' => 'admin'
        ]);

        Route::resource('post_tag', 'Admin\PostTagController', [
            'as' => 'admin'
        ]);
        Route::resource('por_categories', 'Admin\PortfolioCategoriesController', [
            'as' => 'admin'
        ]);


        // categories
        Route::resource('categories', 'Admin\CategoriesController', [
            'as' => 'admin'
        ]);

        // portfolio
        Route::resource('portfolio', 'Admin\PortfolioController', [
            'as' => 'admin'
        ]);
        Route::resource('portfolio_categories', 'Admin\PortfolioCategoriesController', [
            'as' => 'admin'
        ]);
        Route::post('portfolio/clone', 'Admin\PortfolioController@Clone')->name('admin.portfolio.clone');


        // menus
        Route::resource('menus', 'Admin\MenusController', [
            'as' => 'admin'
        ]);

        // widgets
        Route::resource('widgets', 'Admin\WidgetsController', [
            'as' => 'admin'
        ]);
        // media library
        Route::resource('media', 'Admin\MediaController', [
            'as' => 'admin'
        ]);
        //media regenerate thumbnails
        Route::resource('regenerateThumbnails', 'Admin\RegenerateThumbnailsController', [
            'as' => 'admin'
        ]);

        Route::post('/media_popup', 'Admin\MediaController@mediaPopup')->name('media_media_popup');


        Route::resource('/permissions', 'Admin\PermissionsController', [
            'as' => 'admin'
        ]);


        Route::resource('/users', 'Admin\UsersController', [
            'as' => 'admin'
        ]);

        // themes
        Route::resource('/themes', 'Admin\ThemesController', [
            'as' => 'admin'
        ]);
        // plugins
        Route::resource('/plugins', 'Admin\PluginController', [
            'as' => 'admin'
        ]);
        // Options
        Route::resource('/options', 'Admin\OptionsController', [
            'as' => 'admin'
        ]);

        Route::resource('/customize', 'Admin\CustomizeController', [
            'as' => 'admin'
        ]);
    });


    Auth::routes();
    Route::group(['middleware' => 'web'], function () {

        Route::resource('comment', 'Frontend\CommentController', ['only' => ['store']]);
    });


    Route::get('setlocale/{lang}', function ($lang) {

        $referer = Redirect::back()->getTargetUrl(); //Previous page URL

        $parse_url = parse_url($referer, PHP_URL_PATH); //URI previous page


        // break into array by delimiter
        $segments = explode('/', $parse_url);

        // If the URL (where the language switch was clicked) contained the correct language label
        if (in_array($segments[1], getlangsCodes())) {

            unset($segments[1]); //remove label

        }

        // Add a language label to the URL (if you choose a non-default language)
        if ($lang != getOption('LANG', 'en')) {
            array_splice($segments, 1, 0, $lang);
        }

        //we form full URL
        $url = Request::root() . implode("/", $segments);

        //if there were still GET parameters - add them
        if (parse_url($referer, PHP_URL_QUERY)) {
            $url = $url . '?' . parse_url($referer, PHP_URL_QUERY);
        }
        return redirect($url); //Redirect back to the same page.

    })->name('setlocale');

    Route::get('logout', 'Auth\LoginController@logout');

    Route::get('/lr-clear-cache', function () {
        Artisan::call('cache:clear');
        Artisan::call('view:clear');
        return back();
    })->name('lr-clear-cache');
});


// install script

//Route::get( '/lr-install',
//	[
//		'uses' => 'Admin\InstallController',
//		'as' => 'lr-install'
//	] );

app/User.php
<?php

namespace Corp;

use DB;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable {
	use Notifiable;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'name',
		'email',
		'password',
		'login',
		'provider',
		'provider_id',
		'img',
	];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		'password',
		'remember_token',
	];

	public function posts() {
		return $this->hasMany( 'Corp\Post' );
	}

	public function page() {
		return $this->hasMany( 'Corp\Page' );
	}

	public function portfolios() {
		return $this->hasMany( 'Corp\Portfolio' );
	}


	public function roles() {
		return $this->belongsToMany( 'Corp\Role', 'role_user' );
	}

	//  'string'  array('View_Admin','ADD_ARTICLES')
	//
	public function canDo( $permission, $require = FALSE ) {
		if ( is_array( $permission ) ) {
			foreach ( $permission as $permName ) {

				$permName = $this->canDo( $permName );
				if ( $permName && !$require ) {
					return TRUE;
				} else if ( !$permName && $require ) {
					return FALSE;
				}
			}

			return $require;
		} else {
			foreach ( $this->roles as $role ) {
				foreach ( $role->perms as $perm ) {
					//foo*    foobar
					if ( str_is( $permission, $perm->name ) ) {
						return TRUE;
					}
				}
			}
		}
	}

	// string  ['role1', 'role2']
	public function hasRole( $name, $require = false ) {
		if ( is_array( $name ) ) {
			foreach ( $name as $roleName ) {
				$hasRole = $this->hasRole( $roleName );

				if ( $hasRole && !$require ) {
					return true;
				} elseif ( !$hasRole && $require ) {
					return false;
				}
			}
			return $require;
		} else {
			foreach ( $this->roles as $role ) {
				if ( $role->name == $name ) {
					return true;
				}
			}
		}

		return false;
	}

	public function isSuperAdmin() {
		return $this->hasRole( 'Admin' );
	}

	/**
	 * @return mixed
	 */
	public function getTotalUsersPerMoth() {


		$sql = DB::select( "SELECT YEAR(created_at) as Year,
         MONTH(created_at) as Month,
         count(id) AS TotalUsers
    FROM users
GROUP BY YEAR(created_at), MONTH(created_at)
ORDER BY YEAR(created_at), MONTH(created_at);" );

		return $sql;

	}
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace Corp\Http\Controllers\Admin;

use Gate;
use Corp\Http\Requests\UserRequest;
use Illuminate\Http\Request;
use Corp\Repositories\RolesRepository;
use Corp\Repositories\UsersRepository;
use Corp\User;

class UsersController extends   AdminController {

	public function __construct(RolesRepository $rol_rep, UsersRepository $us_rep) {

		parent::__construct();

		$this->baseCms->setAdminCss('jquery.dataTables',asset(config('settings.admin') .'/plugins/components/datatables/jquery.dataTables.min.css'),[],null,10);

		$this->baseCms->setAdminJs( 'jquery.dataTables', asset( config( 'settings.admin' ) . '/plugins/components/datatables/jquery.dataTables.min.js"' ),array( 'jquery' ), '1', true, 10 );


		$this->us_rep = $us_rep;
		$this->rol_rep = $rol_rep;

		$this->template = 'admins.' . config( 'settings.admin' ) . '.index';

	}
		/**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(User  $user)
    {
        //
	    if ( !Gate::allows( 'VIEW_USERS' ) ) {
		    return back()->withErrors( [ __( 'You don\'t have access to do this' ) ] );
		    abort( 403 );

	    }


	    $this->title = __('admin.users');


	    $content = $this->getTemplate( '.users.all-users' ,['users' => $user->with('roles')->get()]);

	    $this->vars = array_add( $this->vars, 'content', $content );
	    return $this->renderOutput();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
	    //
	    if ( !Gate::allows( 'VIEW_USERS' ) ) {
		    return back()->withErrors( [ __( 'You don\'t have access to do this' ) ] );
		    abort( 403 );

	    }
	    $this->title = __('admin.add new user');
	    $roles = $this->getRoles()->reduce(function ($returnRoles, $role) {
		    $returnRoles[$role->id] = $role->name;
		    return $returnRoles;
	    }, []);;

	    $content = $this->getTemplate( '.users.add-user' ,['roles' => $roles]);

	    $this->vars = array_add( $this->vars, 'content', $content );
	    return $this->renderOutput();


    }
	public function getRoles() {
		return \Corp\Role::all();
	}


	/**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        //
	    if ( !Gate::allows( 'EDIT_USERS' ) ) {
		    return back()->withErrors( [ __( 'You don\'t have access to do this' ) ] );
		    abort( 403 );

	    }



	    //
	    $result = $this->us_rep->addUser($request);
	    if(is_array($result) && !empty($result['error'])) {
		    return back()->with($result);
	    }
	    return back()->with($result);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
	    if ( !Gate::allows( 'VIEW_USERS' ) ) {
		    return back()->withErrors( [ __( 'You don\'t have access to do this' ) ] );
		    abort( 403 );

	    }



	    $roles = $this->getRoles()->reduce(function ($returnRoles, $role) {
		    $returnRoles[$role->id] = $role->name;
		    return $returnRoles;
	    }, []);
	    $this->title = __('admin.Edit user'). ' > '. $user->name;


	    $content = $this->getTemplate( '.users.add-user', ['user' => $user, 'roles' => $roles] );

	    $this->vars = array_add( $this->vars, 'content', $content );
	    return $this->renderOutput();

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $user)
    {

	    if ( !Gate::allows( 'EDIT_USERS' ) ) {
		    return back()->withErrors( [ __( 'You don\'t have access to do this' ) ] );
		   // abort( 403 );

	    }
        //
	    $result = $this->us_rep->updateUser($request,$user);

	    if(is_array($result) && !empty($result['error'])) {
		    return back()->with($result);
	    }
	    return back()->with($result);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user, Request $request)
    {
        //
	    if ( !Gate::allows( 'EDIT_USERS' ) ) {
		    return back()->withErrors( [ __( 'You don\'t have access to do this' ) ] );
		    abort( 403 );

	    }
	    $result = $this->us_rep->deleteUser($user);
	    if($request->ajax()) {
		    return json_encode($result);
	    }

	    if(is_array($result) && !empty($result['error'])) {

		    return back()->with($result);
	    }
	    return redirect(route('admin.users.index'))->with($result);
    }
}

resources/views/admins/cubic/users/add-role.blade.php
<div class="container-fluid">
    <!-- /.row -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    @if(isset($user->id))
                        {{__('admin.Edit user')}} "{{$user->name}}"
                    @else
                        {{__('admin.add new user')}}
                    @endif
                </div>
                <div class="panel-wrapper collapse in" aria-expanded="true">
                    <div class="panel-body">
                        <div class="col-md-6">
                            <div class="white-box">
                                <h3 class="box-title m-b-0">{{__('admin.Create a brand new user and add them to this site.')}}
                                </h3>
                                <br>
                                <div class="row">
                                    <div class="col-sm-12 col-xs-12">
                                        <form method="post"
                                              action="{{  (isset($user->id)) ? route('admin.users.update',['users'=>$user->id]) : route('admin.users.store')  }}">
                                            @csrf
                                            @if(isset($user->id))
                                                <input type="hidden" name="_method" value="PUT">

                                            @endif

                                            <div class="form-body">
                                                @if (count($errors) > 0)

                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            @foreach ($errors->all() as $error)
                                                                <div class="alert alert-danger">{{ $error }}</div>
                                                            @endforeach

                                                        </div>

                                                    </div>
                                                @endif

                                                @if (session('status'))
                                                    <div class="row">
                                                        <div class="col-md-12">


                                                            <div class=" alert alert-success">{{ session('status') }}</div>


                                                        </div>
                                                    </div>


                                                @endif


                                                <div class="form-group">
                                                    <label for="exampleInputUsers">{{__('admin.User Name')}}</label>
                                                    <input name="name"
                                                           type="text"
                                                           required class="form-control"
                                                           id="exampleInputUsers"
                                                           value="{{  old('name', isset($user->name) ? $user->name : '' )  }}"
                                                           placeholder="{{__('admin.Enter Username')}}">
                                                </div>

                                                <div class="form-group">
                                                    <label for="exampleInputUsers">{{__('admin.User login')}}</label>
                                                    <input name="login"
                                                           type="text"
                                                           required class="form-control"
                                                           id="exampleInputUsers"
                                                           value="{{  old('login', isset($user->login) ? $user->login : '' )  }}"
                                                           placeholder="{{__('admin.Enter Username')}}">
                                                </div>


                                                <div class="form-group">
                                                    <label for="exampleInputEmail1">{{__('admin.Email address')}}</label>
                                                    <input name="email"
                                                           value="{{  old('email', isset($user->email) ? $user->email : '' )  }}"
                                                           type="email"
                                                           required
                                                           class="form-control"
                                                           id="exampleInputEmail1"
                                                           placeholder="{{__('admin.Enter email')}}">
                                                </div>
                                                <div class="form-group">
                                                    <label for="exampleInputPassword1">{{__('admin.Password')}}</label>
                                                    <input name="password" type="password" class="form-control"
                                                           id="exampleInputPassword1" placeholder="{{__('admin.Password')}}"></div>
                                                <div class="form-group">
                                                    <label for="exampleInputPassword1">{{__('admin.Password')}}</label>
                                                    <input name="password_confirmation" type="password"
                                                           class="form-control" id="exampleInputPassword1"
                                                           placeholder="{{__('admin.Confirm Password')}}"></div>



                                                <div class="form-group">
                                                    <label for="exampleInputEmail1">{{__('admin.Role')}}</label>

                                                </div>

                                                <button type="submit"
                                                        class="btn btn-success waves-effect waves-light m-r-10">
                                                    @if(isset($user->id))
                                                        {{__('admin.Edit user')}}
                                                    @else
                                                        {{__('admin.Add New User')}}
                                                    @endif
                                                </button>


                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/admins/cubic/users/all-users.blade.php
<div class="container-fluid">
    <!-- /.row -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading"> {{__('admin.users')}}    </div>
                <div class="panel-wrapper collapse in" aria-expanded="true">
                    <div class="panel-body">
                        <div class="form-group">
                            <a href="{{route('admin.users.create')}}" type="submit" class="btn  btn-success btn-lg"><i
                                        class="fa fa-user-plus"></i>
                                {{__('admin.add new user')}}
                            </a>
                        </div>



                        <div class="table-responsive ">
                            <table id="example23" class="table  display nowrap" cellspacing="0" width="100%">
                                <thead>
                                <tr>
                                    <th>{{__('admin.ID')}}</th>
                                    <th>{{__('admin.User login')}}</th>
                                    <th>{{__('admin.Name')}}</th>
                                    <th>{{__('admin.Email')}}</th>
                                    <th>{{__('admin.Role')}}</th>
                                    <th>{{__('admin.Actions')}}</th>

                                </tr>
                                </thead>

                                <tbody>
                                @if(isset($users) && is_object($users))
                                    @foreach($users as $user)
                                        <tr>

                                            <td>{{$user->id ?? ''}}</td>
                                            <td>{{$user->login ?? ''}}</td>
                                            <td>
                                                {{$user->name}}

                                            </td>
                                            <td>
                                            {{$user->email}}
                                            <td>
                                                {{  $user->roles->first()->name ?? '' }}

                                            </td>
                                            <td>
                                                <a href="{{ route('admin.users.edit',['users' => $user->id]) }}"
                                                   class="text-inverse p-r-10"
                                                   data-toggle="tooltip" title="" data-original-title="Edit"><i
                                                            class="ti-marker-alt"></i></a>

                                                @if($user->id != 1)

                                                    <a
                                                            href="javascript:void(0)"
                                                            class="text-inverse delete_post"
                                                            title="{{__('admin.Delete')}}"
                                                            data-id="{{$user->id}}"
                                                            data-toggle="tooltip"><i
                                                                class="ti-trash"></i></a>
                                                @endif


                                            </td>


                                        </tr>

                                    @endforeach
                                @endif


                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>


        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>




        <!-- start - This is for export functionality only -->
        {{--<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>--}}
        {{--<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>--}}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
        <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
        <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
        {{--<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>--}}
        {{--<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>--}}
        <!-- end - This is for export functionality only -->

        <script>
            jQuery(document).ready(function ($) {


                $('#example23').DataTable({
                    dom: 'Bfrtip',
                    buttons: [
                        'copyHtml5', 'excelHtml5', 'pdfHtml5', 'csvHtml5'
                    ]
                });


                $("body").on("click", ".delete_post", function (e) {

                    e.preventDefault();
                    $('.preloader').show().css('opacity', '0.3');
                    var this_v = $(this);

                    $.ajax({
                        url: '{{route('admin.users.index')}}/' + $(this).data('id'),
                        type: 'delete', // replaced from put
                        headers: {
                            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                        },
                        success: function (r) {
                            $(this_v).closest('tr').remove();
                            $('.preloader').hide();
                        },
                        error: function (msg) {
                            $('.preloader').hide();
                        }
                    });
                });

            });
        </script>