routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


if (!lr_is_installed()) {

    //Route::group( [ 'middleware' => 'web' ], function () {

    Route::get(
        '/lr-install',
        [
            'uses' => 'Admin\InstallController@showInstall',
        ]
    );
    Route::post(
        '/lr-install',
        [
            'uses' => 'Admin\InstallController@installCms',
        ]
    );
    //});


}


if (!lr_is_installed()) return;
// Localization
Route::get('/js/lang.js', function () {
    $strings = Cache::rememberForever('lang.js', function () {
        $lang = config('app.locale');

        $files = glob(resource_path('lang/' . $lang . '/*.php'));
        $strings = [];

        foreach ($files as $file) {
            $name = basename($file, '.php');
            $strings[$name] = require $file;
        }

        return $strings;
    });

    header('Content-Type: text/javascript');
    echo ('window.i18n = ' . json_encode($strings) . ';');
    exit();
})->name('assets.lang');


// we regenerate thumbails
Route::get('/uploads/{img}/{h}/{w}', function ($filePath, $h = 200, $w = 200) {

    $filePath = public_path("/uploads/$filePath");

    $img = Image::cache(function ($image) use ($filePath, $h, $w) {
        $image->make($filePath)->fit($h, $w); // This line works fine without being wrapped in `cache`
    }, 1, true);


    return $img->response();


    // return Image::make(public_path("/uploads/$filePath"))->fit($h, $w)->response();
});

// we regenerate thumbails
Route::get('storage/uploads/{img}/{h}/{w}', function ($filePath, $h = 200, $w = 200) {

    $filePath = storage_path("app/public/uploads/$filePath");


    $img = Image::cache(function ($image) use ($filePath, $h, $w) {
        $image->make($filePath)->fit($h, $w); // This line works fine without being wrapped in `cache`
    }, 10, true);


    //	dd($filePath);
    return $img->response();


    // return Image::make(public_path("/uploads/$filePath"))->fit($h, $w)->response();
});


Route::group(['prefix' => Corp\Http\Middleware\LocaleMiddleware::getLocale()], function () {


    //admin
    Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {

        //admin
        Route::get(
            '/',
            [
                'uses' => 'Admin\IndexController@index',
                'as' => 'adminIndex'
            ]
        );

        // posts


        Route::resource('posts', 'Admin\PostsController', [
            'as' => 'admin'
        ]);

        Route::post('posts/clone', 'Admin\PostsController@Clone')->name('admin.posts.clone');

        Route::resource('comments', 'Admin\CommentsController', [
            'as' => 'admin'
        ]);

        // comments
        //		Route::resource( 'comments', 'Admin\CommentsController', [
        //			'as' => 'comments'
        //		] );


        // pages
        Route::resource('pages', 'Admin\PageController', [
            'as' => 'admin'
        ]);

        Route::resource('post_tag', 'Admin\PostTagController', [
            'as' => 'admin'
        ]);
        Route::resource('por_categories', 'Admin\PortfolioCategoriesController', [
            'as' => 'admin'
        ]);


        // categories
        Route::resource('categories', 'Admin\CategoriesController', [
            'as' => 'admin'
        ]);

        // portfolio
        Route::resource('portfolio', 'Admin\PortfolioController', [
            'as' => 'admin'
        ]);
        Route::resource('portfolio_categories', 'Admin\PortfolioCategoriesController', [
            'as' => 'admin'
        ]);
        Route::post('portfolio/clone', 'Admin\PortfolioController@Clone')->name('admin.portfolio.clone');


        // menus
        Route::resource('menus', 'Admin\MenusController', [
            'as' => 'admin'
        ]);

        // widgets
        Route::resource('widgets', 'Admin\WidgetsController', [
            'as' => 'admin'
        ]);
        // media library
        Route::resource('media', 'Admin\MediaController', [
            'as' => 'admin'
        ]);
        //media regenerate thumbnails
        Route::resource('regenerateThumbnails', 'Admin\RegenerateThumbnailsController', [
            'as' => 'admin'
        ]);

        Route::post('/media_popup', 'Admin\MediaController@mediaPopup')->name('media_media_popup');


        Route::resource('/permissions', 'Admin\PermissionsController', [
            'as' => 'admin'
        ]);


        Route::resource('/users', 'Admin\UsersController', [
            'as' => 'admin'
        ]);

        // themes
        Route::resource('/themes', 'Admin\ThemesController', [
            'as' => 'admin'
        ]);
        // plugins
        Route::resource('/plugins', 'Admin\PluginController', [
            'as' => 'admin'
        ]);
        // Options
        Route::resource('/options', 'Admin\OptionsController', [
            'as' => 'admin'
        ]);

        Route::resource('/customize', 'Admin\CustomizeController', [
            'as' => 'admin'
        ]);
    });


    Auth::routes();
    Route::group(['middleware' => 'web'], function () {

        Route::resource('comment', 'Frontend\CommentController', ['only' => ['store']]);
    });


    Route::get('setlocale/{lang}', function ($lang) {

        $referer = Redirect::back()->getTargetUrl(); //Previous page URL

        $parse_url = parse_url($referer, PHP_URL_PATH); //URI previous page


        // break into array by delimiter
        $segments = explode('/', $parse_url);

        // If the URL (where the language switch was clicked) contained the correct language label
        if (in_array($segments[1], getlangsCodes())) {

            unset($segments[1]); //remove label

        }

        // Add a language label to the URL (if you choose a non-default language)
        if ($lang != getOption('LANG', 'en')) {
            array_splice($segments, 1, 0, $lang);
        }

        //we form full URL
        $url = Request::root() . implode("/", $segments);

        //if there were still GET parameters - add them
        if (parse_url($referer, PHP_URL_QUERY)) {
            $url = $url . '?' . parse_url($referer, PHP_URL_QUERY);
        }
        return redirect($url); //Redirect back to the same page.

    })->name('setlocale');

    Route::get('logout', 'Auth\LoginController@logout');

    Route::get('/lr-clear-cache', function () {
        Artisan::call('cache:clear');
        Artisan::call('view:clear');
        return back();
    })->name('lr-clear-cache');
});


// install script

//Route::get( '/lr-install',
//	[
//		'uses' => 'Admin\InstallController',
//		'as' => 'lr-install'
//	] );

resources/views/admins/cubic/adminbar.blade.php
<div id="lradminbar" class="">

    <div class="quicklinks" id="lr-toolbar" role="navigation" aria-label="Toolbar" tabindex="0">
        <ul id="lr-admin-bar-root-default" class="ab-top-menu">

            <li id="lr-admin-bar-site-name" class="menupop"><a class="ab-item" aria-haspopup="true"
                                                               href="{{route('adminIndex')}}">{{__('admin.Admin panel')}}</a>
                <div class="ab-sub-wrapper">
                    <ul id="lr-admin-bar-site-name-default" class="ab-submenu">
                        <li id="lr-admin-bar-dashboard"><a class="ab-item"
                                                           href="{{route('adminIndex')}}">{{__('admin.Dashboard')}}</a>
                        </li>
                    </ul>
                    <ul id="lr-admin-bar-appearance" class="ab-submenu">
                        <li id="lr-admin-bar-themes"><a class="ab-item"
                                                        href="{{route( 'admin.themes.index' )}}">{{__('admin.Themes')}}</a>
                        </li>
                        <li id="lr-admin-bar-widgets"><a class="ab-item"
                                                         href="{{route( 'admin.widgets.index' )}}">{{__('admin.Widgets')}}</a>
                        </li>
                        <li id="lr-admin-bar-menus"><a class="ab-item"
                                                       href="{{route( 'admin.menus.index' )}}">{{__('admin.Menus')}}</a>
                        </li>

                    </ul>
                </div>
            </li>

            <li id="lr-admin-bar-edit">

				<?php


				$routeArray = app( 'request' )->route()->getAction();
				$controllerAction = class_basename( $routeArray['controller'] );

				if($controllerAction == 'PostsController@show' && isset( app( 'request' )->route()->controller->post_id )){
				?>
                <a class="ab-item"
                   href="{{route('admin.posts.edit',['id' => app( 'request' )->route()->controller->post_id ])}}">{{__('admin.Edit Post')}}</a>
				<?php  } elseif(isset( app( 'request' )->route()->controller->cat_id )) {
				?>
                <a class="ab-item"
                   href="{{route('admin.categories.edit',['id' => app( 'request' )->route()->controller->cat_id ])}}">{{__('admin.Edit Category')}}</a>
				<?php
				} ?>

                @action('adminbar.edit', $controllerAction)

            </li>

            <li>

                <a class="ab-item"
                   href="{{route('admin.customize.index',['url' =>Request::fullUrl() ])}}">{{__('admin.Customize')}}</a>
            </li>

        </ul>
        <ul id="lr-admin-bar-top-secondary" class="ab-top-secondary ab-top-menu">

            <li id="lr-admin-bar-search" class="admin-bar-search">
                <div class="ab-item ab-empty-item" tabindex="-1">
                    <form action="https://rentit.lrmix.net/" method="get" id="adminbarsearch"><input
                                class="adminbar-input" name="s" id="adminbar-search" type="text" value=""
                                maxlength="150"><label for="adminbar-search"
                                                       class="screen-reader-text">{{__('admin.Search')}}</label><input
                                type="submit"
                                class="adminbar-button"
                                value="Search">
                    </form>
                </div>
            </li>
            <li id="lr-admin-bar-my-account" class="menupop with-avatar"><a class="ab-item" aria-haspopup="true"
                                                                            href="">{{__('admin.Howdy,')}}<span
                            class="display-name">{{$user->name ?? ''}}</span>


                    @if(auth()->user()->img)
                        <img src="{{ the_image_url(auth()->user()->img,'thumbnail-70x70') }}"
                             alt="user-img"
                             class="avatar avatar-26 photo"
                        >

                    @else
                        <img src="{{ asset(config('settings.admin')) }}/plugins/images/users/noavatar.png"
                             alt="user-img"
                             class="avatar avatar-26 photo"
                        >

                    @endif

                </a>
                <div class="ab-sub-wrapper">
                    <ul id="lr-admin-bar-user-actions" class="ab-submenu">
                        <li id="lr-admin-bar-user-info"><a class="ab-item" tabindex="-1"
                                                           href="{{route('admin.users.edit',['users' => auth()->user()->id])}}">

                                @if(auth()->user()->img)
                                    <img src="{{ the_image_url(auth()->user()->img,'thumbnail-70x70') }}"
                                         alt="user-img"
                                         class="avatar avatar-64 photo"
                                    >

                                @else
                                    <img src="{{ asset(config('settings.admin')) }}/plugins/images/users/noavatar.png"
                                         alt="user-img"
                                         class="avatar avatar-64 photo"
                                    >

                                @endif


                                <span
                                        class="display-name">{{ Auth::user()->name }}</span></a></li>
                        <li id="lr-admin-bar-edit-profile"><a class="ab-item"
                                                              href="{{route('admin.users.edit',['id' => $user->id ])}}">{{__('admin.Edit My Profile')}}</a>
                        </li>
                        <li id="lr-admin-bar-logout"><a class="ab-item"
                                                        href="{{route('logout')}}">{{__('admin.Log Out')}}</a></li>
                    </ul>
                </div>
            </li>


            @action('adminbar.center', $controllerAction)
            <li id="lr-admin-bar-comet_cache-clear" class="-clear"><a class="ab-item" tabindex="-1"
                                                                      href="{{route('lr-clear-cache')}}">{{__('admin.Clear Cache')}}</a>
            </li>
        </ul>
    </div>
    <a class="screen-reader-shortcut" href="{{route('logout')}}">{{__('admin.Log Out')}}</a>
</div>

resources/views/admins/cubic/content.blade.php
{{--<div class="container-fluid">--}}
    {{--<div class="col-md-12"><h1>{{__('admin.Dashboard')}}</h1></div>--}}
{{--</div>--}}

<!-- ===== Page-Container ===== -->
<div class="container-fluid">
    @action('dashboard.top-widget')
    <div >
        <div class="white-box">
            <div class="text-center">
                <h1 class="">{{__('admin.Welcome to Lararent!')}}  <small>v {{ config('settings.lr_version') }}</small></h1>

                <p>{{__('admin.We’ve assembled some links to get you started:')}}</p></div>

                <div class="row default-steps">
                    <div class="col-md-4 column-step">
                        <div class="step-number">{{__('admin.1')}}</div>
                        <div class="step-title">{{__('admin.Get Started')}}</div>
                        <div class="step-info">

                            <a class="btn  btn-success btn-lg"
                               href="{{route('admin.customize.index')}}">{{__('admin.Customize Your Site')}}</a>

                            <p class="hide-if-no-customize">{{__('admin.or,')}}
                                <a href="{{route('admin.themes.index')}}">{{__('admin.change your theme completely')}}</a></p>

                            <br><br>
                            <br>
                        </div>
                    </div>
                    <div class="col-md-4 column-step active">
                        <div class="step-number">{{__('admin.2')}}</div>
                        <div class="step-title">{{__('admin.Next Steps')}}</div>
                        <div class="step-info">
                            <div class="list-group">

                                <a href="{{route('admin.pages.create')}}" class="list-group-item active">{{__('admin.Add additional pages')}}</a>
                                <a href="{{route('admin.posts.create')}}" class="list-group-item active">{{__('admin.Add additional posts')}}</a>
                                <a href="{{ url('/') }}" class="list-group-item active">{{__('admin.View your site')}}</a>
                            </div>

                       </div>
                    </div>
                    <div class="col-md-4 column-step">
                        <div class="step-number">{{__('admin.3')}}</div>
                        <div class="step-title">{{__('admin.More Actions')}}</div>
                        <div class="step-info">
                            <div class="list-group">
                                <span class="list-group-item active">
                                   {{__('admin.Manage')}} <a href="{{route('admin.widgets.index')}}" class="text-white">
                                        {{__('admin.widgets')}}</a> {{__('admin.or')}}  <a href="{{route('admin.menus.index')}}" class="text-white">{{__('admin.menus')}}</a>
                                </span>


                                <a href="{{route('admin.users.index')}}" class="list-group-item">{{__('admin.Manage users')}}</a>
                                <a href="{{route('admin.options.index')}}" class="list-group-item">{{__('admin.Change options')}}</a>
                            </div>

                      </div>
                    </div>


        </div>
    </div>
    <!-- ===== Right-Sidebar-End ===== -->
</div>
    @action('dashboard.bottom-widget')
</div>

<!-- ===== Page-Container-End ===== -->

resources/views/admins/cubic/index.blade.php
@extends('admins.' . config('settings.admin'). '.layouts.admin')

@section('sidebar-left')
    {!! $sidebar_left !!}
@endsection

@section('content')
    {!! $content !!}
@endsection

resources/views/admins/cubic/media.blade.php
<div class="container-fluid">
    <!-- /.row -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">{{__('admin.Media')}}</div>
                <div class="panel-wrapper collapse in" aria-expanded="true">
                    <div class="panel-body">


                        <div class="row el-element-overlay m-b-20">
                            <div class="white-box">
                            <div class="col-md-12">
                                <div id="resss"></div>

                                    <h3 class="box-title m-b-0">{{__('admin.Drop images to upload')}}</h3>
                                    <p class="text-muted m-b-30"></p>
                                    <form id="media_uploader" class="dropzone"
                                          action="{{route('admin.media.store')}}" method="post"
                                          enctype="multipart/form-data">
                                        @csrf

                                        <div class="preview">

                                        <div class="fallback">
                                            <input name="file" type="file" multiple/></div>


                                        <div class="col-md-12 media_container">
                                           {!! $medias ?? '' !!}
                                        </div>


                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>


            @yield('right-sidebar')

        </div>
    </div>
</div>

<?php  $edit_places_id = 0; ?>


<style>


</style>

<script>
    $(document).ready(function () {


        /*
         ajax paginagion
         */
        var page = 1;

        $(window).scroll(function() {
            if(($(window).scrollTop() + $(window).height() + 800 ) >= $(document).height()) {
                page++;
                //alert(1);
                loadMoreData(page);
            } else {
                console.log($(window).scrollTop() + $(window).height()  , $(document).height());
            }
        });


        function loadMoreData(page){
            $.ajax(
                {
                    url: '{{route('admin.media.index')}}?page=' + page,
                    type: "get",
                    data: 'ajax_load_page=1',
                    beforeSend: function()
                    {
                        $('.ajax-load').show();
                    }
                })
                .done(function(data)                {

                    $('.ajax-load').hide();
                    $('.media_container').append(data);
                    start_popup();

                })
                .fail(function(jqXHR, ajaxOptions, thrownError)
                {
                   // alert('server not responding...');
                });
        }





        /**
         *  Delete media
         * */
        $(".media_container").on("click", ".delete_media", function () {
            var this_v = $(this);
            var this_id = this_v.data('id');


            swal({
                title: "Media will be deleted permanently!",
                text: "Are you sure to proceed?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, Remove Media!",
                cancelButtonText: "No, I am not sure!",
                // closeOnConfirm: false,
                // closeOnCancel: false
            }).then(function (isConfirm) {


                // alert(isConfirm);
                if (isConfirm.value) {

                    $.ajax({
                        url: medialibrary_obj.store + '/' + this_id,
                        type: 'delete', // replaced from put
                        headers: {
                            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                        },
                        success: function (r) {
                            $(this_v).closest('.media-item').remove();

                        },
                        error: function (msg) {
                            $('.preloader').hide();
                            console.log(msg.responseJSON.message);
                            swal({
                                title: "Error!",
                                text: msg.responseJSON.message,
                                type: "error",
                                showCancelButton: false,
                                confirmButtonColor: "#DD6B55",

                            })
                        }
                    });



                }
                else {

                }

            });


        });



        var $ajax_url = '{{route('admin.media.store')}}';
        var city2_obj = {
            'delete': '1',
            'upload': '1'

        };


        var myDropzone1;
        jQuery("#media_uploader").dropzone({

            init: function () {
                myDropzone1 = this;

                jQuery.ajax({
                    url: $ajax_url,
                    method: 'POST',
                    headers: {
                        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                    },
                    type: 'gat',
                    data: {somefield: "Some field value", _token: '{{csrf_token()}}'},
                    success: function (data) {
                        //   console.log(data);
                        /* jQuery.each(data, function (key, value) {
                        var mockFile = {name: value.name, size: value.size, attachment_id: value.id};
                        myDropzone1.emit("addedfile", mockFile);
                        myDropzone1.createThumbnailFromUrl(mockFile, value.url);
                        myDropzone1.emit("complete", mockFile);
                        });*/
                    }
                });
            },
        });

        // myDropzone1.on("queuecomplete", function (file) {
        //     alert("All files have uploaded ");
        // });


        myDropzone1.on("success", function (file) {
            var new_item = $(file.xhr.responseText).hide();
            $('.media_container').prepend(new_item);
            new_item.show('normal');
            start_popup();

        });


        myDropzone1.on("addedfile", function (file) {
            $('#media_uploader').prepend($(file.previewElement));
        });


        function  start_popup() {
            $('.image-popup-vertical-fit').magnificPopup({
                type: 'image',
                closeOnContentClick: true,
                mainClass: 'mfp-img-mobile',
                image: {
                    verticalFit: true
                }

            });
        }





    });


</script>

resources/views/admins/cubic/mediaLibraryModal.blade.php
<div id="mediaLibrary-modal" class="modal fade" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true" style="">
    <div class="modal-dialog media-modal-dialog" style="width: 100%">
        <div class="modal-content media-modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">×
                </button>
                <h4 class="modal-title"> {{__('admin.Media library')}}</h4></div>
            <div class="modal-body">
                <div class="cssload-speeding-wheel"></div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger waves-effect"
                        data-dismiss="modal"> {{__('admin.Close')}}
                </button>
                <button type="button"
                        data-dismiss="modal"
                        class="btn btn-success waves-effect waves-light insert_img_new">
                    {{__('admin.Insert image')}}
                </button>
            </div>
        </div>
    </div>
</div>

resources/views/admins/cubic/sidebar-left.blade.php
<aside class="sidebar">
    <div class="scroll-sidebar">
        <div class="user-profile">
            <div class="dropdown user-pro-body">
                <div class="profile-image">
                    {{--<img src="{{ asset(config('settings.admin')) }}/plugins/images/users/noavatar.png" alt="user-img"--}}
                    {{--class="img-circle">   --}}


                    @if(auth()->user()->img)
                        <img src="{{ the_image_url(auth()->user()->img,'thumbnail-70x70') }}"
                             alt="user-img"
                             class="img-circle"
                        >

                    @else
                        <img src="{{ asset(config('settings.admin')) }}/plugins/images/users/noavatar.png"
                             alt="user-img"
                             class="img-circle"
                        >

                    @endif

                    <a href="javascript:void(0);" class="dropdown-toggle u-dropdown text-blue" data-toggle="dropdown"
                       role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="badge badge-danger">
                                    <i class="fa fa-angle-down"></i>
                                </span>
                    </a>
                    <ul class="dropdown-menu animated flipInY">
                        <li><a href="{{route('admin.users.edit',['users' => $user->id])}}"><i
                                        class="fa fa-user"></i>{{__('admin.Profile')}}</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{route('admin.users.edit',['users' => $user->id])}}"><i
                                        class="fa fa-cog"></i>{{__('admin.Account Settings')}}</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{route('logout')}}"><i class="fa fa-power-off"></i>{{__('admin.Logout')}}</a></li>
                    </ul>
                </div>
                <p class="profile-text m-t-15 font-16"><a href="javascript:void(0);">{{$user->name}}</a></p>
            </div>
        </div>
        <nav class="sidebar-nav">
            <ul id="side-menu">

                @if(isset($backendMenu))
                    @foreach($backendMenu as $k => $v)

						<?php
						$allow = true;
						$auth_user =  Auth::user();

						if ( isset( $v['permissions'] ) && is_array( $v['permissions'] ) ) {
							foreach ( $v['permissions'] as $permission ) {
								$allow = $auth_user->can( $permission ) ? $auth_user->can( $permission ) : $auth_user->canDo( $permission ) ;
							}

						} elseif ( isset( $v['permissions'] ) ) {
							$allow =$auth_user->can( $v['permissions'] ) ?  $auth_user->can( $v['permissions'] ) : $auth_user->canDo( $v['permissions'] );

						}
						if($allow){

						$path = str_replace( request()->root() . '/', '', $v['url'] );


						?>


                        <li @if(request()->is($path.'/*')) class="active" @endif>

                            <a class=" waves-effect"

                               @if(!isset($v['sideMenu']))
                               href="{{$v['url']}}"
                               @else   href="javascript:void(0);"
                               @endif
                               aria-expanded="false"><i
                                        class="{{$v['icon'] ?? ''}} fa-fw"></i>
                                <span class="hide-menu"> {{$v['name'] ?? ''}}

                                    @if(isset($v['label']))
                                        <span class="label label-rounded label-info pull-right">{{$v['label']}}</span></span>
                                @endif
                            </a>

                            @if(isset($v['sideMenu']))
                                <ul aria-expanded="false" class="collapse">
                                    @foreach($v['sideMenu'] as $sideMenu)
										<?php
										$allowSide = true;

										$path = str_replace( request()->root() . '/', '', $sideMenu['url'] );


										if ( isset( $sideMenu['permissions'] ) && is_array( $sideMenu['permissions'] ) ) {
											foreach ( $sideMenu['permissions'] as $permission ) {

												$allowSide = $auth_user->can( $permission ) ? $auth_user->can( $permission ) : $auth_user->canDo( $permission );
											}

										} elseif ( isset( $v['permissions'] ) ) {
											$allowSide  =$auth_user->can( $v['permissions'] ) ?  $auth_user->can( $v['permissions'] ) : $auth_user->canDo( $v['permissions'] );

										}
										if($allowSide){
										?>
                                        <li @if(request()->is($path.'/*')) class="active" @endif><a
                                                    href="{{ $sideMenu['url'] ?? '' }}">{{ $sideMenu['name'] ?? '' }}</a>
                                        </li>
										<?php  } ?>

                                    @endforeach
                                </ul>
                            @endif
                        </li>
						<?php  } ?>

                    @endforeach
                @endif


            </ul>
        </nav>

    </div>
</aside>