routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


if (!lr_is_installed()) {

    //Route::group( [ 'middleware' => 'web' ], function () {

    Route::get(
        '/lr-install',
        [
            'uses' => 'Admin\InstallController@showInstall',
        ]
    );
    Route::post(
        '/lr-install',
        [
            'uses' => 'Admin\InstallController@installCms',
        ]
    );
    //});


}


if (!lr_is_installed()) return;
// Localization
Route::get('/js/lang.js', function () {
    $strings = Cache::rememberForever('lang.js', function () {
        $lang = config('app.locale');

        $files = glob(resource_path('lang/' . $lang . '/*.php'));
        $strings = [];

        foreach ($files as $file) {
            $name = basename($file, '.php');
            $strings[$name] = require $file;
        }

        return $strings;
    });

    header('Content-Type: text/javascript');
    echo ('window.i18n = ' . json_encode($strings) . ';');
    exit();
})->name('assets.lang');


// we regenerate thumbails
Route::get('/uploads/{img}/{h}/{w}', function ($filePath, $h = 200, $w = 200) {

    $filePath = public_path("/uploads/$filePath");

    $img = Image::cache(function ($image) use ($filePath, $h, $w) {
        $image->make($filePath)->fit($h, $w); // This line works fine without being wrapped in `cache`
    }, 1, true);


    return $img->response();


    // return Image::make(public_path("/uploads/$filePath"))->fit($h, $w)->response();
});

// we regenerate thumbails
Route::get('storage/uploads/{img}/{h}/{w}', function ($filePath, $h = 200, $w = 200) {

    $filePath = storage_path("app/public/uploads/$filePath");


    $img = Image::cache(function ($image) use ($filePath, $h, $w) {
        $image->make($filePath)->fit($h, $w); // This line works fine without being wrapped in `cache`
    }, 10, true);


    //	dd($filePath);
    return $img->response();


    // return Image::make(public_path("/uploads/$filePath"))->fit($h, $w)->response();
});


Route::group(['prefix' => Corp\Http\Middleware\LocaleMiddleware::getLocale()], function () {


    //admin
    Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {

        //admin
        Route::get(
            '/',
            [
                'uses' => 'Admin\IndexController@index',
                'as' => 'adminIndex'
            ]
        );

        // posts


        Route::resource('posts', 'Admin\PostsController', [
            'as' => 'admin'
        ]);

        Route::post('posts/clone', 'Admin\PostsController@Clone')->name('admin.posts.clone');

        Route::resource('comments', 'Admin\CommentsController', [
            'as' => 'admin'
        ]);

        // comments
        //		Route::resource( 'comments', 'Admin\CommentsController', [
        //			'as' => 'comments'
        //		] );


        // pages
        Route::resource('pages', 'Admin\PageController', [
            'as' => 'admin'
        ]);

        Route::resource('post_tag', 'Admin\PostTagController', [
            'as' => 'admin'
        ]);
        Route::resource('por_categories', 'Admin\PortfolioCategoriesController', [
            'as' => 'admin'
        ]);


        // categories
        Route::resource('categories', 'Admin\CategoriesController', [
            'as' => 'admin'
        ]);

        // portfolio
        Route::resource('portfolio', 'Admin\PortfolioController', [
            'as' => 'admin'
        ]);
        Route::resource('portfolio_categories', 'Admin\PortfolioCategoriesController', [
            'as' => 'admin'
        ]);
        Route::post('portfolio/clone', 'Admin\PortfolioController@Clone')->name('admin.portfolio.clone');


        // menus
        Route::resource('menus', 'Admin\MenusController', [
            'as' => 'admin'
        ]);

        // widgets
        Route::resource('widgets', 'Admin\WidgetsController', [
            'as' => 'admin'
        ]);
        // media library
        Route::resource('media', 'Admin\MediaController', [
            'as' => 'admin'
        ]);
        //media regenerate thumbnails
        Route::resource('regenerateThumbnails', 'Admin\RegenerateThumbnailsController', [
            'as' => 'admin'
        ]);

        Route::post('/media_popup', 'Admin\MediaController@mediaPopup')->name('media_media_popup');


        Route::resource('/permissions', 'Admin\PermissionsController', [
            'as' => 'admin'
        ]);


        Route::resource('/users', 'Admin\UsersController', [
            'as' => 'admin'
        ]);

        // themes
        Route::resource('/themes', 'Admin\ThemesController', [
            'as' => 'admin'
        ]);
        // plugins
        Route::resource('/plugins', 'Admin\PluginController', [
            'as' => 'admin'
        ]);
        // Options
        Route::resource('/options', 'Admin\OptionsController', [
            'as' => 'admin'
        ]);

        Route::resource('/customize', 'Admin\CustomizeController', [
            'as' => 'admin'
        ]);
    });


    Auth::routes();
    Route::group(['middleware' => 'web'], function () {

        Route::resource('comment', 'Frontend\CommentController', ['only' => ['store']]);
    });


    Route::get('setlocale/{lang}', function ($lang) {

        $referer = Redirect::back()->getTargetUrl(); //Previous page URL

        $parse_url = parse_url($referer, PHP_URL_PATH); //URI previous page


        // break into array by delimiter
        $segments = explode('/', $parse_url);

        // If the URL (where the language switch was clicked) contained the correct language label
        if (in_array($segments[1], getlangsCodes())) {

            unset($segments[1]); //remove label

        }

        // Add a language label to the URL (if you choose a non-default language)
        if ($lang != getOption('LANG', 'en')) {
            array_splice($segments, 1, 0, $lang);
        }

        //we form full URL
        $url = Request::root() . implode("/", $segments);

        //if there were still GET parameters - add them
        if (parse_url($referer, PHP_URL_QUERY)) {
            $url = $url . '?' . parse_url($referer, PHP_URL_QUERY);
        }
        return redirect($url); //Redirect back to the same page.

    })->name('setlocale');

    Route::get('logout', 'Auth\LoginController@logout');

    Route::get('/lr-clear-cache', function () {
        Artisan::call('cache:clear');
        Artisan::call('view:clear');
        return back();
    })->name('lr-clear-cache');
});


// install script

//Route::get( '/lr-install',
//	[
//		'uses' => 'Admin\InstallController',
//		'as' => 'lr-install'
//	] );

resources/views/admins/cubic/pages/all-pages.blade.php
<div class="container-fluid">
    <!-- /.row -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading"> {{__('admin.Pages')}}</div>
                <div class="panel-wrapper collapse in" aria-expanded="true">
                    <div class="panel-body">


                        <div class="form-group row">
                            <div class="col-md-9">
                                <a href="{{ route('admin.pages.create') }}" type="submit" class="btn  btn-success btn-lg"><i class="fa fa-user-plus"></i>
                                    {{__('admin.Add new Page')}}

                                </a>
                            </div>

                            <div class="col-md-3 col-xs-12 pull-right">
                                <form action="{{route('admin.pages.index')}}" method="GET">
                                    <div class="row">

                                        <div class="input-group">
                                            <input name="search" value="{{$request->search ?? ''}}" type="text"
                                                   class="form-control" placeholder="Search"/>
                                            <div class="input-group-btn">
                                                <button class="btn btn-primary" type="submit">
                                                    <span class="glyphicon glyphicon-search"></span>
                                                </button>
                                            </div>
                                        </div>

                                    </div>
                                </form>


                            </div>

                        </div>
                        @if($request->search ?? false)
                            <h3>{{__('Search result for'). ' "'. $request->search . '"'}}  </h3>
                        @endif

                        <div class="table-responsive ">

                            <table class="table product-overview " id="myTable">
                                <thead>
                                <tr>
                                    <th>{{__('admin.Title')}}</th>
                                    <th>{{__('admin.Author')}}
                                    </th>
                                    <th> {{__('admin.Tags')}}</th>
                                    <th><i class="ti-comment-alt"></i></th>
                                    <th>{{__('admin.Date')}}</th>
                                    <th>{{__('admin.Status')}}</th>
                                    <th>{{__('admin.Actions')}}</th>
                                </tr>
                                </thead>
                                <tbody>

                                @if(isset($pages) && is_object($pages))
                                    @foreach($pages as $post)



                                        <tr>
                                            <td>
                                                <a href="{{  route('admin.pages.edit',['pages'=>$post->id])  }}">
                                                    @if($post->img > 0)
                                                        <img src="{{ the_image_url($post->img,'thumbnail-260x260') }}"
                                                             alt="{{$post->title}}"
                                                             width="80">
                                                    @endif

                                                    {{$post->title}}</a>
                                            </td>

                                            <td>
                                                {{--<img src="http://lararent.test/cubic/plugins/images/users/hanna.jpg" alt="iMac"--}}
                                                {{--width="80">--}}
                                                {{----}}
                                                {{$post->user->name}}
                                            </td>
                                            <td>....</td>
                                            <td>0</td>
                                            <td>{{$post->created_at->format('d-m-Y') ?? ''}}</td>
                                            <td><span class="label label-success font-weight-100">{{__('admin.Published')}}</span></td>
                                            <td>
                                                <a href="{{  route('admin.pages.edit',['pages'=>$post->id])  }}"
                                                   class="text-inverse p-r-10" data-toggle="tooltip"
                                                   title="{{__('admin.Edit')}}"><i class="ti-marker-alt"></i></a>

                                                <a
                                                        href="javascript:void(0)"
                                                        class="text-inverse delete_post"
                                                        title="{{__('admin.Delete')}}"
                                                        data-id="{{$post->id}}"
                                                        data-toggle="tooltip"><i
                                                            class="ti-trash"></i></a></td>
                                        </tr>
                                    @endforeach

                                @endif
                                </tbody>
                            </table>
                            @if($pages->isEmpty())
                                <h6>{{__('admin.Nothing found...')}}</h6>
                        @endif
                            <!-- Pagination -->
                            <div class="pagination-wrapper">
                                <ul class="pagination">
                                    @if($pages->currentPage() !== 1)
                                        <li class="disabled"><a href="{{$pages->url(($pages->currentPage() - 1))}}">
                                                <i class="fa fa-angle-double-left"></i></a></li>

                                    @endif

                                    @for($i = 1; $i <= $pages->lastPage(); $i++)
                                        @if($pages->currentPage() == $i)

                                            <li class="active"><a href="#">{{ $i }}
                                                    <span class="sr-only"></span></a>
                                            </li>
                                        @else

                                            <li><a href="{{ $pages->url($i) }}">{{ $i }}</a></li>
                                        @endif
                                    @endfor

                                    @if($pages->currentPage() !== $pages->lastPage())

                                        <li><a href="{{ $pages->url(($pages->currentPage() + 1)) }}"> <i
                                                        class="fa fa-angle-double-right"></i></a></li>
                                    @endif

                                </ul>
                            </div>
                            <!-- /Pagination -->


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


<script>
    $(document).ready(function () {


        $("body").on("click", ".delete_post", function (e) {

            e.preventDefault();
            $('.preloader').show().css('opacity', '0.3');
            var this_v = $(this);

            $.ajax({
                url: '{{route('admin.pages.index')}}/' + $(this).data('id'),
                type: 'delete', // replaced from put
                headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                },
                success: function (r) {
                    res = JSON.parse(r);
                    if(res.deleted) {
                        $(this_v).closest('tr').remove();
                        $('.preloader').hide();
                    }
                },
                error: function (msg) {
                    $('.preloader').hide();
                }
            });
        });

    });

</script>