routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


if (!lr_is_installed()) {

    //Route::group( [ 'middleware' => 'web' ], function () {

    Route::get(
        '/lr-install',
        [
            'uses' => 'Admin\InstallController@showInstall',
        ]
    );
    Route::post(
        '/lr-install',
        [
            'uses' => 'Admin\InstallController@installCms',
        ]
    );
    //});


}


if (!lr_is_installed()) return;
// Localization
Route::get('/js/lang.js', function () {
    $strings = Cache::rememberForever('lang.js', function () {
        $lang = config('app.locale');

        $files = glob(resource_path('lang/' . $lang . '/*.php'));
        $strings = [];

        foreach ($files as $file) {
            $name = basename($file, '.php');
            $strings[$name] = require $file;
        }

        return $strings;
    });

    header('Content-Type: text/javascript');
    echo ('window.i18n = ' . json_encode($strings) . ';');
    exit();
})->name('assets.lang');


// we regenerate thumbails
Route::get('/uploads/{img}/{h}/{w}', function ($filePath, $h = 200, $w = 200) {

    $filePath = public_path("/uploads/$filePath");

    $img = Image::cache(function ($image) use ($filePath, $h, $w) {
        $image->make($filePath)->fit($h, $w); // This line works fine without being wrapped in `cache`
    }, 1, true);


    return $img->response();


    // return Image::make(public_path("/uploads/$filePath"))->fit($h, $w)->response();
});

// we regenerate thumbails
Route::get('storage/uploads/{img}/{h}/{w}', function ($filePath, $h = 200, $w = 200) {

    $filePath = storage_path("app/public/uploads/$filePath");


    $img = Image::cache(function ($image) use ($filePath, $h, $w) {
        $image->make($filePath)->fit($h, $w); // This line works fine without being wrapped in `cache`
    }, 10, true);


    //	dd($filePath);
    return $img->response();


    // return Image::make(public_path("/uploads/$filePath"))->fit($h, $w)->response();
});


Route::group(['prefix' => Corp\Http\Middleware\LocaleMiddleware::getLocale()], function () {


    //admin
    Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {

        //admin
        Route::get(
            '/',
            [
                'uses' => 'Admin\IndexController@index',
                'as' => 'adminIndex'
            ]
        );

        // posts


        Route::resource('posts', 'Admin\PostsController', [
            'as' => 'admin'
        ]);

        Route::post('posts/clone', 'Admin\PostsController@Clone')->name('admin.posts.clone');

        Route::resource('comments', 'Admin\CommentsController', [
            'as' => 'admin'
        ]);

        // comments
        //		Route::resource( 'comments', 'Admin\CommentsController', [
        //			'as' => 'comments'
        //		] );


        // pages
        Route::resource('pages', 'Admin\PageController', [
            'as' => 'admin'
        ]);

        Route::resource('post_tag', 'Admin\PostTagController', [
            'as' => 'admin'
        ]);
        Route::resource('por_categories', 'Admin\PortfolioCategoriesController', [
            'as' => 'admin'
        ]);


        // categories
        Route::resource('categories', 'Admin\CategoriesController', [
            'as' => 'admin'
        ]);

        // portfolio
        Route::resource('portfolio', 'Admin\PortfolioController', [
            'as' => 'admin'
        ]);
        Route::resource('portfolio_categories', 'Admin\PortfolioCategoriesController', [
            'as' => 'admin'
        ]);
        Route::post('portfolio/clone', 'Admin\PortfolioController@Clone')->name('admin.portfolio.clone');


        // menus
        Route::resource('menus', 'Admin\MenusController', [
            'as' => 'admin'
        ]);

        // widgets
        Route::resource('widgets', 'Admin\WidgetsController', [
            'as' => 'admin'
        ]);
        // media library
        Route::resource('media', 'Admin\MediaController', [
            'as' => 'admin'
        ]);
        //media regenerate thumbnails
        Route::resource('regenerateThumbnails', 'Admin\RegenerateThumbnailsController', [
            'as' => 'admin'
        ]);

        Route::post('/media_popup', 'Admin\MediaController@mediaPopup')->name('media_media_popup');


        Route::resource('/permissions', 'Admin\PermissionsController', [
            'as' => 'admin'
        ]);


        Route::resource('/users', 'Admin\UsersController', [
            'as' => 'admin'
        ]);

        // themes
        Route::resource('/themes', 'Admin\ThemesController', [
            'as' => 'admin'
        ]);
        // plugins
        Route::resource('/plugins', 'Admin\PluginController', [
            'as' => 'admin'
        ]);
        // Options
        Route::resource('/options', 'Admin\OptionsController', [
            'as' => 'admin'
        ]);

        Route::resource('/customize', 'Admin\CustomizeController', [
            'as' => 'admin'
        ]);
    });


    Auth::routes();
    Route::group(['middleware' => 'web'], function () {

        Route::resource('comment', 'Frontend\CommentController', ['only' => ['store']]);
    });


    Route::get('setlocale/{lang}', function ($lang) {

        $referer = Redirect::back()->getTargetUrl(); //Previous page URL

        $parse_url = parse_url($referer, PHP_URL_PATH); //URI previous page


        // break into array by delimiter
        $segments = explode('/', $parse_url);

        // If the URL (where the language switch was clicked) contained the correct language label
        if (in_array($segments[1], getlangsCodes())) {

            unset($segments[1]); //remove label

        }

        // Add a language label to the URL (if you choose a non-default language)
        if ($lang != getOption('LANG', 'en')) {
            array_splice($segments, 1, 0, $lang);
        }

        //we form full URL
        $url = Request::root() . implode("/", $segments);

        //if there were still GET parameters - add them
        if (parse_url($referer, PHP_URL_QUERY)) {
            $url = $url . '?' . parse_url($referer, PHP_URL_QUERY);
        }
        return redirect($url); //Redirect back to the same page.

    })->name('setlocale');

    Route::get('logout', 'Auth\LoginController@logout');

    Route::get('/lr-clear-cache', function () {
        Artisan::call('cache:clear');
        Artisan::call('view:clear');
        return back();
    })->name('lr-clear-cache');
});


// install script

//Route::get( '/lr-install',
//	[
//		'uses' => 'Admin\InstallController',
//		'as' => 'lr-install'
//	] );

app/Post.php
<?php

namespace Corp;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    //
	use SoftDeletes;
	use Translatable;

	// trnalstions filds
	public $translatedAttributes = ['title', 'desc', 'text','keywords','meta_desc'];


//	protected $guarded = ['id'];
	//protected $guarded = ['id'];
	protected $fillable = ['img','alias','status','published_at'];


	protected $dates = [
		'created_at',
		'updated_at',
		'deleted_at',
		'published_at'


	];
	public function user() {
		return $this->belongsTo('Corp\User');
	}

//	public function category() {
//		return $this->belongsTo('Corp\Category');
//	}

	public function categories()
	{
		//return $this->hasMany(Category::class);
		return $this->belongsToMany('Corp\Category');
	}

	public function comments()
	{

		return $this->hasMany('Corp\Comment');
	}
	public function meta()
	{
		return $this->morphMany('Corp\Meta', 'metable');
	}
	public function tags(){
		return $this->belongsToMany('Corp\Tag','tag_post');
	}
//	public function translations()
//	{
//		return $this->belongsTo('Corp\PostTranslation');
//	}

}

//class PostTranslation extends Model
//{
//	public $timestamps = false;
//	protected $guarded = ['id'];
//
//}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace Corp\Http\Controllers\Admin;

use App;
use Auth;
use Cache;
use Corp\Category;
use Corp\Country;
use Corp\Http\Requests\PostRequest;
use Corp\Post;
use Corp\Repositories\CategoriesRepository;
use Corp\Repositories\PostsRepository;
use Corp\Tag;
use Gate;
use Illuminate\Http\Request;


class PostsController extends AdminController {


	public function __construct( PostsRepository $p_rep, CategoriesRepository $c_rep, Category $category ) {
		$this->middleware( 'auth' );


		parent::__construct();


		$this->baseCms->setAdminCss( 'Magnific', asset( config( 'settings.admin' ) . '/plugins/components/Magnific-Popup-master/dist/magnific-popup.css' ), [], null, 10 );
		$this->baseCms->setAdminCss( 'icheck', asset( config( 'settings.admin' ) . '/plugins/components/icheck/skins/square/_all.css' ), [], null, 10 );
		$this->baseCms->setAdminCss( 'bootstrap-tagsinput', asset( config( 'settings.admin' ) . '/plugins/components/bootstrap-tagsinput/dist/bootstrap-tagsinput.css' ), [], null, 10 );
		$this->baseCms->setAdminCss( 'bootstrap-datetimepicker', asset( config( 'settings.admin' ) . '/plugins/components/bootstrap-datetimepicker-master/build/css/bootstrap-datetimepicker.min.css' ), [], null, 10 );


		//	$this->baseCms->setAdminJs( 'PostsController', asset( config( 'settings.admin' ) . '/js/PostsController.min.js ' ), array( 'jquery' ), '1', false, 10 );

		$this->baseCms->setAdminJs( 'icheck', asset( config( 'settings.admin' ) . '/plugins/components/icheck/icheck.js' ), array( 'jquery' ), '1', true, 10 );
		$this->baseCms->setAdminJs( 'icheck-init', asset( config( 'settings.admin' ) . '/plugins/components/icheck/icheck.init.js' ), array( 'jquery' ), '1', true, 10 );
		$this->baseCms->setAdminJs( 'moment-with-locales', asset( config( 'settings.admin' ) . '/plugins/components/bootstrap-datetimepicker-master/moment-with-locales.min.js' ), array( 'jquery' ), '1', true, 10 );
		$this->baseCms->setAdminJs( 'bootstrap-datetimepicker', asset( config( 'settings.admin' ) . '/plugins/components/bootstrap-datetimepicker-master/build/js/bootstrap-datetimepicker.min.js' ),
			array( 'jquery', 'moment-with-locales' ), '2', true, 10 );
		$this->baseCms->setAdminJs( 'typeahead', asset( config( 'settings.admin' ) . '/js/typeahead.bundle.js' ), array( 'jquery' ), '1', true, 10 );
		$this->baseCms->setAdminJs( 'tagsinput', asset( config( 'settings.admin' ) . '/plugins/components/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js' ), array( 'jquery' ), '1', true, 10 );

		$this->baseCms->setAdminJs( 'tinymce', asset( config( 'settings.admin' ) . '/plugins/components/tinymce/js/tinymce/tinymce.js' ), array( 'jquery' ), '1', false, 10 );


		$this->p_rep = $p_rep;
		$this->c_rep = $c_rep;
		$this->template = 'admins.' . config( 'settings.admin' ) . '.index';


	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index( Request $request, Post $post ) {
		//


		if ( !Gate::allows( 'VIEW_ADMIN_POSTS' ) ) {
			return back();
			abort( 403 );
		}


		$this->title = __( 'admin.All Posts' );
		$posts = $post->with( 'translations', 'user' )->latest( 'created_at' );

		if ( $request->search ) {
			$posts = $posts->whereHas(
				'translations',
				function ( $query ) use ( $request ) {
					$query->where( 'title', 'like', '%' . $request->search . '%' );
					$query->where( 'locale', App::getLocale() );
				}
			);
		}


		$posts = $posts->paginate( config( 'lararent.item_per_page', 10 ) );
		$content = $this->getTemplate( '.posts.all-posts', [ 'posts' => $posts, 'request' => $request ] );


		$this->vars = array_add( $this->vars, 'content', $content );

		return $this->renderOutput();
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create( Category $category ) {
		//
		if ( !Gate::allows( 'ADD_POSTS' ) ) {
			//return back();
			//abort( 403 );
		}
		$this->title = __( 'admin.Add post' );
		$this->title = 'Lararent';

		$categories = $this->c_rep->transliterateAll( $category->with( 'translations' )->get()->groupBy( 'parent_id' ) );

		$category_list = buildUlCheckboxOptions( buildTree( $categories->toArray(), 0 ) );


		$tags = Tag::with( 'translations' )->get();


		$content = $this->getTemplate( '.posts.add-post',
			[

				'category_list' => $category_list,
				'tags' => $tags,

			] );


		$this->vars = array_add( $this->vars, 'content', $content );

		return $this->renderOutput();
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @return \Illuminate\Http\Response
	 */
	public function store( PostRequest $request ) {
		//

		if ( !Gate::allows( 'ADD_POSTS' ) ) {
			return back()->withErrors( [ __( 'You don\'t have access to store this post' ) ] );
			abort( 403 );
		}

		$result = $this->p_rep->addPost( $request );

		//	dd($result);
		if ( is_array( $result ) && isset( $result['id'] ) ) {
			return redirect( route( 'admin.posts.edit', [ 'posts' => $result['id'] ] ) )->with( $result );
		}
		if ( is_array( $result ) && !empty( $result['error'] ) ) {

			return back()->with( $result );
		}

		return back()->with( $result );
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 * @return \Illuminate\Http\Response
	 */
	public function show( $id ) {
		//
	}

	/**
	 * Show the form for editing Post.
	 *
	 * @param  int $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit( Category $category, $id ) {
		//

		$post = Post::with( [ 'translations', 'categories' ] )->where( 'id', $id )->first();
		$this->title = __( 'admin.Edit post' ) . ' > ' . $post->title;
		if ( !Gate::allows( 'VIEW_ADMIN_POSTS', $post ) ) {
			return back()->withErrors( [ __( 'You don\'t have access to edit this post' ) ] );

			abort( 403 );
		}


		$categories = $this->c_rep->transliterateAll( $category->with( 'translations' )->get() );

		// we get array of categories id that attach to post you also can use array_pluck
		$post_categories = [];

		foreach ( $post->categories as $k => $v ) {
			$post_categories[] = $categories->find( $v->id )->id;


		}


		$categories = $categories->groupBy( 'parent_id' );

		$category_list = buildUlCheckboxOptions( buildTree( $categories->toArray(), 0 ), $post_categories );


		$tags = Tag::with( 'translations' )->get();
		$post_tags = $post->tags()->with( 'translations' )->get();
		$attached_tag = [];
		foreach ( $post_tags as $item ) {
			$attached_tag[] = $item->title;

		}
		$attached_tag = implode( ',', $attached_tag );

		$content = $this->getTemplate( '.posts.add-post',
			[
				'post' => $post,
				'category_list' => $category_list,
				'tags' => $tags,
				'attached_tag' => $attached_tag
			] );


		$this->vars = array_add( $this->vars, 'content', $content );

		return $this->renderOutput();

	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  int $id
	 * @return \Illuminate\Http\Response
	 */
	public function update( PostRequest $request, Post $post ) {
		//


		if ( !Gate::allows( 'UPDATE_POSTS' ) ) {
			return back()->withErrors( [ __( 'You don\'t have access to change this portfolio' ) ] );
			abort( 403 );
		}

		$result = $this->p_rep->updatePost( $request, $post );
		//dd($request);

		if ( is_array( $result ) && !empty( $result['error'] ) ) {
			return back()->with( $result );
		}

		return back()->with( $result );

	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy( Post $post, \Illuminate\Http\Request $request ) {
		//

		abort_unless( Gate::allows( 'DELETE_POSTS' ), 403 );

		$result = $this->p_rep->deletePost( $post );

		if ( is_array( $result ) && !empty( $result['error'] ) ) {
			if ( $request->ajax() && $request->ajax_load_page ) {
				return json_encode( $request );
			}
			return back()->with( $result );
		}
		if ( $request->ajax() ) {
			return json_encode( $request );
		}
		return redirect( '/admin' )->with( $result );

	}


	public function getPosts() {
		//

		//return $this->p_rep->get('*',false,true);
		return $this->p_rep->get();


	}

	public function clone( Request $request ) {

		if ( Gate::allows( 'ADD_POSTS' ) ) {


			$post = new Post();


			$old = $post->with( 'translations', 'user', 'categories' )->where( 'id', (int) $request->posts )->first();


			list( $alias, $i ) = $this->p_rep->generateAlias( $alias ?? $old->alias );


			$request->request->add( $old->getAttributes() );
			$request->request->add( $old->translations()->first()->getAttributes() );
			$request->request->add( [ 'alias' => $alias ] );
			$request->request->add( [ 'title' => $old->title . ' ' . $i ] );


			$request->request->add( [ 'category_id' => $old->categories->pluck( 'id' )->toArray() ] );

			$meta = $old->meta()->get();
			$post_meta = [];
			foreach ( $meta as $item ) {
				if ( $item->value == '' ) {
					$post_meta[$item->name] = $item->translation_value;
					$request->request->add( [ $item->name => json_decode( $item->translation_value, true ) ?? $item->translation_value ] );
				} else {
					$request->request->add( [ $item->name => json_decode( $item->value, true ) ?? $item->value ] );
					$post_meta[$item->name] = $item->value;
				}

			}


			$result = $this->p_rep->addPost( $request );


			$post = $post->where( 'id', $result['id'] )->first();

			return $this->getTemplate( '.posts.post_item', compact( 'post' ) );
		}
	}
}

resources/views/admins/cubic/posts/all-posts.blade.php
<div class="container-fluid">
    <!-- /.row -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading"> {{__('admin.Posts')}}</div>
                <div class="panel-wrapper collapse in" aria-expanded="true">
                    <div class="panel-body">
                        <div class="form-group row">
                            <div class="col-md-9">
                                <a href="{{ route('admin.posts.create') }}" type="submit"
                                   class="btn  btn-success btn-lg"><i
                                            class="fa fa-user-plus"></i>
                                    {{__('admin.Add new post')}}
                                </a>
                            </div>

                            <div class="col-md-3 col-xs-12 pull-right">
                                <form action="{{route('admin.posts.index')}}" method="GET">
                                    <div class="row">

                                        <div class="input-group">
                                            <input name="search" value="{{$request->search ?? ''}}" type="text"
                                                   class="form-control" placeholder="Search"/>
                                            <div class="input-group-btn">
                                                <button class="btn btn-primary" type="submit">
                                                    <span class="glyphicon glyphicon-search"></span>
                                                </button>
                                            </div>
                                        </div>

                                    </div>
                                </form>


                            </div>

                        </div>
                        @if($request->search ?? false)
                            <h3>{{__('Search result for'). ' "'. $request->search . '"'}}  </h3>
                        @endif

                        <div class="table-responsive ">


                            <table class="table product-overview " id="myTable">
                                <thead>
                                <tr>
                                    <th>{{__('admin.Title')}}</th>
                                    <th>{{__('admin.Categories')}}</th>
                                    <th>{{__('admin.Author')}}
                                    </th>
                                    <th> {{__('admin.Tags')}}</th>
                                    <th><i class="ti-comment-alt"></i></th>
                                    <th>{{__('admin.Date')}}</th>
                                    <th>{{__('admin.Status')}}</th>
                                    <th>{{__('admin.Actions')}}</th>
                                </tr>
                                </thead>
                                <tbody>

                                @if(isset($posts) && is_object($posts))
                                    @foreach($posts as $post)
                                        @include( 'admins.'.config('settings.admin').'.posts.post_item')

                                    @endforeach


                                @endif
                                </tbody>
                            </table>

                            @if($posts->isEmpty())
                             <h6>{{__('admin.Nothing found...')}}</h6>
                            @endif

                        </div>


                        <!-- /Blog posts -->

                        <!-- Pagination -->
                        <div class="pagination-wrapper">
                            <ul class="pagination">
                                @if($posts->currentPage() !== 1)
                                    <li class="disabled"><a href="{{$posts->url(($posts->currentPage() - 1))}}">
                                            <i class="fa fa-angle-double-left"></i></a></li>

                                @endif

                                @for($i = 1; $i <= $posts->lastPage(); $i++)
                                    @if($posts->currentPage() == $i)

                                        <li class="active"><a href="#">{{ $i }}
                                                <span class="sr-only"></span></a>
                                        </li>
                                    @else

                                        <li><a href="{{ $posts->url($i) }}">{{ $i }}</a></li>
                                    @endif
                                @endfor

                                @if($posts->currentPage() !== $posts->lastPage())

                                    <li><a href="{{ $posts->url(($posts->currentPage() + 1)) }}"> <i
                                                    class="fa fa-angle-double-right"></i></a></li>
                                @endif

                            </ul>
                        </div>
                        <!-- /Pagination -->


                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


<script>
    $(document).ready(function () {


        $("body").on("click", ".delete_post", function (e) {

            e.preventDefault();
            $('.preloader').show().css('opacity', '0.3');
            var this_v = $(this);

            $.ajax({
                url: '{{route('admin.posts.index')}}/' + $(this).data('id'),
                type: 'delete', // replaced from put
                headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                },
                success: function (r) {
                    $(this_v).closest('tr').remove();
                    $('.preloader').hide();
                },
                error: function (msg) {
                    $('.preloader').hide();
                }
            });
        });


        $("body").on("click", "a.clone_post", function (e) {

            e.preventDefault();
            $('.preloader').show().css('opacity', '0.3');
            var this_v = $(this);


            $.ajax({
                url: this_v.attr('href'),
                type: 'post', // replaced from put
                headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                },
                success: function (r) {
                    $('.preloader').hide();
                    //  $('.result').html(r);
                    this_v.closest('tr').before(r);
                    //      $('.products-items').append(r);
                    console.log(r);
                },
                error: function (msg) {
                    $('.preloader').hide();
                }
            });
        });

    });

</script>

resources/views/admins/cubic/posts/post_item.blade.php
<tr>
    <td>
        <a href="{{  route('admin.posts.edit',['posts'=>$post->id])  }}">
            @if($post->img > 0)
                <img src="{{ the_image_url($post->img,'thumbnail-260x260') }}"
                     alt="{{$post->title}}"
                     width="80">
            @endif

            {{$post->title}}</a>
    </td>
    <td>{{$post->category->title ?? ''}}</td>
    <td>
        {{--<img src="http://lararent.test/cubic/plugins/images/users/hanna.jpg" alt="iMac"--}}
        {{--width="80">--}}
        {{----}}
        {{$post->user->name}}
    </td>
    <td>....</td>
    <td>0</td>
    <td>{{$post->created_at->format('d-m-Y') ?? ''}}</td>
    <td><span class="label label-success font-weight-100">{{__('admin.Published')}}</span></td>
    <td>
        <a href="{{  route('admin.posts.clone',['posts'=>$post->id])  }}"
           class="text-inverse p-r-10 clone_post" data-toggle="tooltip"
           title="{{__('admin.Clone')}}">
            <i class="fa fa-clone"></i></a>

        <a href="{{  route('admin.posts.edit',['posts'=>$post->id])  }}"
           class="text-inverse p-r-10" data-toggle="tooltip"
           title="{{__('admin.Edit')}}"><i class="ti-marker-alt"></i></a>

        <a
                href="javascript:void(0)"
                class="text-inverse delete_post"
                title="{{__('admin.Delete')}}"
                data-id="{{$post->id}}"
                data-toggle="tooltip"><i
                    class="ti-trash"></i></a></td>
</tr>